 Answer with the type of stats test you would use (assume normal distribution):

Do students get better test grades if they have a rubber duck on their desk?  
T-Test, one-tail

Does smoking affect whether or not someone has lung cancer?  
Chi Squared

Is gender independent of a person’s blood type?  
Chi Squared

A farming company wants to know if a new fertilizer has improved crop yield or not  
T-Test, two-tail

Does the length of time of the lecture correlate with a students grade?  
PearsonR

Do people with dogs live in apartments more than people with cats?  
Chi Squared

Use the following contingency table to help answer the question of whether using a macbook and being a codeup student are independent of each other.

                        Codeup Student	Not Codeup Student
Uses a Macbook	        49	            20
Doesn't Use A Macbook	1	            30

Choose another 2 categorical variables from the mpg dataset and perform a 
chi2 contingency table test with them. Be sure to state your null and alternative hypotheses.

In [2]:
import pandas as pd
from scipy import stats
from pydataset import data
import numpy as np

mpg = data('mpg')
mpg.head()

#Is variable: Manufacturer independent of variable: class?
#Manufacturer is independent of class
#Manufacturer is not independent of class

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [4]:
observed = pd.crosstab(mpg.manufacturer, mpg['class'])
observed

class         2seater  compact  midsize  minivan  pickup  subcompact  suv
manufacturer                                                             
audi                0       15        3        0       0           0    0
chevrolet           5        0        5        0       0           0    9
dodge               0        0        0       11      19           0    7
ford                0        0        0        0       7           9    9
honda               0        0        0        0       0           9    0
hyundai             0        0        7        0       0           7    0
jeep                0        0        0        0       0           0    8
land rover          0        0        0        0       0           0    4
lincoln             0        0        0        0       0           0    3
mercury             0        0        0        0       0           0    4
nissan              0        2        7        0       0           0    4
pontiac             0        0        5        0       0           0    0
subaru              0        4        0        0       0           4    6
toyota              0       12        7        0       7           0    8
volkswagen          0       14        7        0       0           6    0

In [5]:
chi2, p, degf, expected = stats.chi2_contingency(observed)
chi2, p, degf, expected

(464.37214690582,
 5.267718408816259e-54,
 84,
 array([[0.38461538, 3.61538462, 3.15384615, 0.84615385, 2.53846154,
         2.69230769, 4.76923077],
        [0.40598291, 3.81623932, 3.32905983, 0.89316239, 2.67948718,
         2.84188034, 5.03418803],
        [0.79059829, 7.43162393, 6.48290598, 1.73931624, 5.21794872,
         5.53418803, 9.8034188 ],
        [0.53418803, 5.02136752, 4.38034188, 1.17521368, 3.52564103,
         3.73931624, 6.62393162],
        [0.19230769, 1.80769231, 1.57692308, 0.42307692, 1.26923077,
         1.34615385, 2.38461538],
        [0.2991453 , 2.81196581, 2.45299145, 0.65811966, 1.97435897,
         2.09401709, 3.70940171],
        [0.17094017, 1.60683761, 1.4017094 , 0.37606838, 1.12820513,
         1.1965812 , 2.11965812],
        [0.08547009, 0.8034188 , 0.7008547 , 0.18803419, 0.56410256,
         0.5982906 , 1.05982906],
        [0.06410256, 0.6025641 , 0.52564103, 0.14102564, 0.42307692,
         0.44871795, 0.79487179],
        [0.08547009, 0.803

In [6]:
# print 'Observed Values' followed by a new line
print('Observed Values\n')

# print the values from the 'observed' dataframe
print(observed.values)

# print --- and then a new line, 'Expected Values', followed by another new line
print('---\nExpected Values\n')

# print the expected values array
print(expected.astype(int))

# print a new line
print('---\n')

# print the chi2 value, formatted to a float with 4 digits. 
print(f'chi^2 = {chi2:.4f}') 

# print the p-value, formatted to a float with 4 digits. 
print(f'p     = {p:.4f}')

Observed Values

[[ 0 15  3  0  0  0  0]
 [ 5  0  5  0  0  0  9]
 [ 0  0  0 11 19  0  7]
 [ 0  0  0  0  7  9  9]
 [ 0  0  0  0  0  9  0]
 [ 0  0  7  0  0  7  0]
 [ 0  0  0  0  0  0  8]
 [ 0  0  0  0  0  0  4]
 [ 0  0  0  0  0  0  3]
 [ 0  0  0  0  0  0  4]
 [ 0  2  7  0  0  0  4]
 [ 0  0  5  0  0  0  0]
 [ 0  4  0  0  0  4  6]
 [ 0 12  7  0  7  0  8]
 [ 0 14  7  0  0  6  0]]
---
Expected Values

[[0 3 3 0 2 2 4]
 [0 3 3 0 2 2 5]
 [0 7 6 1 5 5 9]
 [0 5 4 1 3 3 6]
 [0 1 1 0 1 1 2]
 [0 2 2 0 1 2 3]
 [0 1 1 0 1 1 2]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 2 2 0 1 1 3]
 [0 1 0 0 0 0 1]
 [0 2 2 0 1 2 3]
 [0 6 5 1 4 5 9]
 [0 5 4 1 3 4 7]]
---

chi^2 = 464.3721
p     = 0.0000


Use the data from the employees database to answer these questions:

Is an employee's gender independent of whether an employee works in sales or marketing? (only look at current employees)

Is an employee's gender independent of whether or not they are or have been a manager?